import {
    createAsyncThunk,
    createSlice,
} from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import { _saveQuestionAnswer } from '../../utils/_DATA';
import User from '../../utils/user';
import Answer from '../../utils/answer';

export interface AnswerQuestionState {
    status: 'idle' | 'loading' | 'failed';
}

const initialState: AnswerQuestionState = {
    status: 'idle',
};

export const postAnswer = createAsyncThunk(
    'answer/post',
    async ({ authedUser, answer }: { authedUser: User, answer: Answer }) => {
        const response = await _saveQuestionAnswer({ authedUser, answer });
        return response;
    }
);

export const answerQuestionSlice = createSlice({
    name: 'answer',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(postAnswer.pending, (state) => {
                state.status = 'loading';
            })
            .addCase(postAnswer.fulfilled, (state) => {
                state.status = 'idle';
            })
            .addCase(postAnswer.rejected, (state) => {
                state.status = 'failed';
            });
    },
});

export const status = (state: RootState) => state.questionsState.status;

export default answerQuestionSlice.reducer;