import { createAsyncThunk, createSelector, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import { _getUsers } from '../../utils/_DATA';
import User from '../../utils/user';

export interface UsersState {
    users: { [key: string]: User };
    status: 'idle' | 'loading' | 'failed';
}

const initialState: UsersState = {
    users: {},
    status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchUsers = createAsyncThunk(
    'users/fetchUsers',
    async () => {
        const response = await _getUsers();
        return response.users;
    }
);

export const usersSlice = createSlice({
    name: 'users',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchUsers.pending, (state) => {
                state.status = 'loading';
            })
            .addCase(fetchUsers.fulfilled, (state, action: PayloadAction<{ [key: string]: User }>) => {
                state.status = 'idle';
                state.users = action.payload;
            })
            .addCase(fetchUsers.rejected, (state) => {
                state.status = 'failed';
            });
    },
});

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const allUsers = (state: RootState) => state.users.users;

export const status = (state: RootState) => state.users.status;

export const sortedUsersForLeadearboad = createSelector(
    (state: RootState) => [...Object.values(state.users.users)],
    (users: User[]) => users.sort((a: User, b: User) => {
            const aTotal = Object.keys(a.answers).length;
            const bTotal = Object.keys(b.answers).length;
            return bTotal - aTotal;
        }));

export default usersSlice.reducer;
